#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["AECS.Delivery.Api/AECS.Delivery.Api.csproj", "AECS.Delivery.Api/"]
RUN dotnet restore "AECS.Delivery.Api/AECS.Delivery.Api.csproj"
COPY . .
WORKDIR "/src/AECS.Delivery.Api"
RUN dotnet build "AECS.Delivery.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AECS.Delivery.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AECS.Delivery.Api.dll"]